export type ResourceState = "loose" | "fluid" | "unit";

export interface Resource {
  id: string;
  name: string;
  state: ResourceState;
}

export const resources = {
  seaWater: { id: "seaWater", name: "Sea Water", state: "fluid" },
  water: { id: "water", name: "Water", state: "fluid" },
  brine: { id: "brine", name: "Brine", state: "fluid" },
  steamDepleted: { id: "steamDepleted", name: "Steam (Depleted)", state: "fluid" },
  steamSuper: { id: "steamSuper", name: "Steam (Super)", state: "fluid" },
  steamHigh: { id: "steamHigh", name: "Steam (High)", state: "fluid" },
  steamLow: { id: "steamLow", name: "Steam (Low)", state: "fluid" },
  coreFuel: { id: "coreFuel", name: "Core Fuel", state: "unit" },
  coreFuelSpent: { id: "coreFuelSpent", name: "Core Fuel (Spent)", state: "unit" },
  blanketFuel: { id: "blanketFuel", name: "Blanket Fuel", state: "unit" },
  blanketFuelEnriched: { id: "blanketFuelEnriched", name: "Blanket Fuel (Enriched)", state: "unit" },
  hydrogen: { id: "hydrogen", name: "Hydrogen", state: "fluid" },
  oxygen: { id: "oxygen", name: "Oxygen", state: "fluid" },
  enrichedUranium4: { id: "enrichedUranium4", name: "Enriched Uranium (4%)", state: "unit" },
  enrichedUranium20: { id: "enrichedUranium20", name: "Enriched Uranium (20%)", state: "unit" },
  moxRod: { id: "moxRod", name: "MOX Rod", state: "unit" },
  salt: { id: "salt", name: "Salt", state: "loose" },
  plutonium: { id: "plutonium", name: "Plutonium", state: "unit" },
  sulfur: { id: "sulfur", name: "Sulfur", state: "loose" },
  acid: { id: "acid", name: "Acid", state: "fluid" },
  naphtha: { id: "naphtha", name: "Naphtha", state: "fluid" },
  ethanol: { id: "ethanol", name: "Ethanol", state: "fluid" },
  carbonDioxide: { id: "carbonDioxide", name: "Carbon Dioxide", state: "fluid" },
  graphite: { id: "graphite", name: "Graphite", state: "loose" },
  rubber: { id: "rubber", name: "Rubber", state: "unit" },
  impureCopper: { id: "impureCopper", name: "Impure Copper", state: "unit" },
  copper: { id: "copper", name: "Copper", state: "unit" },
  moltenGlass: { id: "moltenGlass", name: "Molten Glass", state: "fluid" },
  steel: { id: "steel", name: "Steel", state: "unit" },
  fissionProduct: { id: "fissionProduct", name: "Fission Product", state: "unit" },
  retiredWaste: { id: "retiredWaste", name: "Retired Waste", state: "unit" },
  recyclables: { id: "recyclables", name: "Recyclables", state: "loose" },
  depletedUranium: { id: "depletedUranium", name: "Depleted Uranium", state: "unit" },
  yellowcake: { id: "yellowcake", name: "Yellowcake", state: "loose" },
  spentFuel: { id: "spentFuel", name: "Spent Fuel", state: "unit" },
  spentMox: { id: "spentMox", name: "Spent MOX", state: "unit" },
  uraniumOre: { id: "uraniumOre", name: "Uranium Ore", state: "loose" },
  uraniumOrePowder: { id: "uraniumOrePowder", name: "Uranium Ore Powder", state: "loose" },
  foodPack: { id: "foodPack", name: "Food Pack", state: "unit" },
  gold: { id: "gold", name: "Gold", state: "unit" },
  ironOre: { id: "ironOre", name: "Iron Ore", state: "loose" },
  labEquipmentIv: { id: "labEquipmentIv", name: "Lab Equipment IV", state: "unit" },
  toxicSlurry: { id: "toxicSlurry", name: "Toxic Slurry", state: "fluid" },
  hydrogenFluoride: { id: "hydrogenFluoride", name: "Hydrogen Fluoride", state: "fluid" },
  titaniumAlloy: { id: "titaniumAlloy", name: "Titanium Alloy", state: "unit" },
  mechanicalParts: { id: "mechanicalParts", name: "Mechanical Parts", state: "unit" },
  electronicsI: { id: "electronicsI", name: "Electronics I", state: "unit" },
  electronicsII: { id: "electronicsII", name: "Electronics II", state: "unit" },
  electronicsIII: { id: "electronicsIII", name: "Electronics III", state: "unit" },
  electronicsIv: { id: "electronicsIv", name: "Electronics IV", state: "unit" },
  maintenanceI: { id: "maintenanceI", name: "Maintenance I", state: "unit" },
  maintenanceII: { id: "maintenanceII", name: "Maintenance II", state: "unit" },
  maintenanceIII: { id: "maintenanceIII", name: "Maintenance III", state: "unit" },
  compactReactor: { id: "compactReactor", name: "Compact Reactor", state: "unit" },
  electricity: { id: "electricity", name: "Electricity", state: "unit" },
} as const satisfies Record<string, Resource>;

export type ResourceId = keyof typeof resources;
