import {
  Atom,
  Bird,
  Boxes,
  Cloud,
  Construction,
  FlaskConical,
  Pickaxe,
  Rocket,
  Satellite,
  Server,
  Sprout,
  Sun,
  TreePine,
  type LucideIcon,
  Users,
  Wrench,
} from "lucide-react";

export const moduleIcons: Partial<Record<string, LucideIcon>> = {
  general: Boxes,
  forestry: TreePine,
  "process-steam": Cloud,
  research: FlaskConical,
  "space-station": Satellite,
  "space-points-expansion": Rocket,
  greenhouses: Sprout,
  "chicken-farms": Bird,
  housing: Users,
  "static-infrastructure": Construction,
  mines: Pickaxe,
  nuclear: Atom,
  "solar-power": Sun,
  computing: Server,
  maintenance: Wrench,
};
