import {
  Atom,
  Bird,
  Archive,
  Boxes,
  BriefcaseBusiness,
  Cloud,
  Construction,
  FlaskConical,
  Pickaxe,
  Satellite,
  Sprout,
  TreePine,
  type LucideIcon,
} from "lucide-react";

export const moduleIcons: Partial<Record<string, LucideIcon>> = {
  general: Boxes,
  forestry: TreePine,
  "process-steam": Cloud,
  research: FlaskConical,
  offices: BriefcaseBusiness,
  "space-station": Satellite,
  greenhouses: Sprout,
  "chicken-farms": Bird,
  "static-infrastructure": Construction,
  mines: Pickaxe,
  reserves: Archive,
  nuclear: Atom,
};
