import {
  defaultMaintenanceStatueCount,
  maintenanceStatue,
} from "../maintenance-statue";
import { type Module } from "./modules";

export const GENERAL_MODULE_ID = "general";

export const general: Module = {
  id: GENERAL_MODULE_ID,
  name: "General",
  description: "Shared production for yellowcake, electronics, and supporting materials",
  builtBuildings: {
    "crusher-large": 1,
    "settling-tank": 2,
    "mixer-ii-acid": 1,
    "assembly-v-electronics-i": 1,
    "assembly-v-electronics-ii": 1,
    "assembly-v-pcb": 1,
    "assembly-v-food-pack-eggs": 1,
    "assembly-v-food-pack-meat": 1,
    "arc-furnace-ii-silicon": 1,
    "silicon-reactor-poly-silicon": 1,
    "crystallizer-silicon-wafer": 1,
    "microchip-machine-ii-1a": 1,
    "microchip-machine-ii-1b": 1,
    "microchip-machine-ii-1c": 1,
    "microchip-machine-ii-2a": 1,
    "microchip-machine-ii-2b": 1,
    "microchip-machine-ii-2c": 1,
    "microchip-machine-ii-3a": 1,
    "microchip-machine-ii-3b": 1,
    "microchip-machine-ii-3c": 1,
    "microchip-machine-ii-4a": 1,
    "microchip-machine-ii-4b": 1,
    "microchip-machine-ii-final": 1,
    "assembly-v-electronics-iii": 1,
    "rubber-maker-ethanol": 1,
    "chemical-plant-ii-ethanol": 1,
    "chemical-plant-ii-graphite": 1,
    "chemical-plant-ii-graphite-coal": 1,
    "copper-electrolysis-acid": 2,
    "waste-sorting-recyclables": 1,
    "exhaust-scrubber-limestone": 1,
    "glass-maker-ii": 1,
    "arc-furnace-ii-glass-broken": 1,
    "arc-furnace-ii-glass-mix": 1,
    "mixer-ii-glass-mix-acid": 1,
    "arc-furnace-ii-copper-scrap": 1,
    "arc-furnace-ii-copper-ore": 1,
    "metal-caster-ii-copper": 2,
    "crusher-large-copper": 1,
    "gold-furnace-scrap": 1,
    "gold-furnace-concentrate": 1,
    "settling-tank-gold": 1,
    "crusher-large-gold-crushing": 1,
    "crusher-large-gold-milling": 1,
    "assembly-v-medical-supplies-i": 1,
    "assembly-v-medical-equipment": 1,
    "chemical-plant-ii-disinfectant": 1,
    "mixer-ii-filter-media-manufactured-sand": 1,
    "crusher-large-rock-to-gravel": 1,
    "crusher-large-gravel-to-manufactured-sand": 1,
    "coal-maker-wood": 1,
    "crusher-large-titanium": 1,
    "arc-furnace-ii-titanium-ore": 1,
    "chemical-plant-ii-titanium-chlorination": 1,
    "chemical-plant-ii-titanium-reduction": 1,
    "arc-furnace-ii-titanium-sponge": 1,
    "alloy-mixer-titanium": 1,
    "cooled-caster-ii-titanium-alloy": 1,
    "electrolyzer-ii-chlorine": 1,
    "mill-wheat": 4,
    "mill-canola-cooking-oil": 1,
    "baking-unit-bread": 3,
    "baking-unit-cake": 1,
    "food-processor-snack": 1,
    "food-processor-sugar": 1,
    "food-processor-sausage": 1,
    "food-processor-tofu": 1,
    "mixer-ii-animal-feed-corn": 1,
    "mixer-ii-biomass-compost": 1,
    "air-separator-nitrogen": 1,
    "chemical-plant-ii-ammonia": 1,
    "anaerobic-digester-meat-trimmings": 1,
    "cracking-unit-fuel-gas-diesel": 1,
    "mixer-ii-organic-fertilizer-dirt": 1,
    "chemical-plant-ii-fertilizer-i-organic": 1,
    "mixer-ii-fertilizer-ii": 1,
    "mixer-ii-dirt-from-compost": 1,
    "polymerization-plant-plastic-ethanol": 1,
    "assembly-v-mechanical-parts": 1,
    "cooled-caster-ii-steel": 1,
    "oxygen-furnace-ii-steel": 1,
    "arc-furnace-ii-iron-scrap": 1,
    "arc-furnace-ii-iron-ore": 1,
    "crusher-large-iron": 1,
    "wastewater-treatment-toxic-slurry": 1,
    "evaporation-pond-heated-salt-brine": 1,
    [maintenanceStatue.id]: defaultMaintenanceStatueCount,
  },
  presets: [
    {
      id: "yellowcake",
      name: "Yellowcake",
      description: "Yellowcake production balanced against factory demand",
      builtBuildings: {
        "crusher-large": 1,
        "settling-tank": 2,
        "mixer-ii-acid": 1,
        "assembly-v-electronics-i": 1,
        "assembly-v-electronics-ii": 1,
        "assembly-v-pcb": 1,
        "assembly-v-food-pack-eggs": 1,
        "assembly-v-food-pack-meat": 1,
        "arc-furnace-ii-silicon": 1,
        "silicon-reactor-poly-silicon": 1,
        "crystallizer-silicon-wafer": 1,
        "microchip-machine-ii-1a": 1,
        "microchip-machine-ii-1b": 1,
        "microchip-machine-ii-1c": 1,
        "microchip-machine-ii-2a": 1,
        "microchip-machine-ii-2b": 1,
        "microchip-machine-ii-2c": 1,
        "microchip-machine-ii-3a": 1,
        "microchip-machine-ii-3b": 1,
        "microchip-machine-ii-3c": 1,
        "microchip-machine-ii-4a": 1,
        "microchip-machine-ii-4b": 1,
        "microchip-machine-ii-final": 1,
        "assembly-v-electronics-iii": 1,
        "rubber-maker-ethanol": 1,
        "chemical-plant-ii-ethanol": 1,
        "chemical-plant-ii-graphite": 1,
        "chemical-plant-ii-graphite-coal": 1,
        "copper-electrolysis-acid": 2,
        "waste-sorting-recyclables": 1,
        "exhaust-scrubber-limestone": 1,
        "glass-maker-ii": 1,
        "arc-furnace-ii-glass-broken": 1,
        "arc-furnace-ii-glass-mix": 1,
        "mixer-ii-glass-mix-acid": 1,
        "arc-furnace-ii-copper-scrap": 1,
        "arc-furnace-ii-copper-ore": 1,
        "metal-caster-ii-copper": 2,
        "crusher-large-copper": 1,
        "gold-furnace-scrap": 1,
        "gold-furnace-concentrate": 1,
        "settling-tank-gold": 1,
        "crusher-large-gold-crushing": 1,
        "crusher-large-gold-milling": 1,
        "assembly-v-medical-supplies-i": 1,
        "assembly-v-medical-equipment": 1,
        "chemical-plant-ii-disinfectant": 1,
        "mixer-ii-filter-media-manufactured-sand": 1,
        "crusher-large-rock-to-gravel": 1,
        "crusher-large-gravel-to-manufactured-sand": 1,
        "coal-maker-wood": 1,
        "crusher-large-titanium": 1,
        "arc-furnace-ii-titanium-ore": 1,
        "chemical-plant-ii-titanium-chlorination": 1,
        "chemical-plant-ii-titanium-reduction": 1,
        "arc-furnace-ii-titanium-sponge": 1,
        "alloy-mixer-titanium": 1,
        "cooled-caster-ii-titanium-alloy": 1,
        "electrolyzer-ii-chlorine": 1,
        "mill-wheat": 4,
        "mill-canola-cooking-oil": 1,
        "baking-unit-bread": 3,
        "baking-unit-cake": 1,
        "food-processor-snack": 1,
        "food-processor-sugar": 1,
        "food-processor-sausage": 1,
        "food-processor-tofu": 1,
        "mixer-ii-animal-feed-corn": 1,
        "mixer-ii-biomass-compost": 1,
        "air-separator-nitrogen": 1,
        "chemical-plant-ii-ammonia": 1,
        "anaerobic-digester-meat-trimmings": 1,
        "cracking-unit-fuel-gas-diesel": 1,
        "mixer-ii-organic-fertilizer-dirt": 1,
        "chemical-plant-ii-fertilizer-i-organic": 1,
        "mixer-ii-fertilizer-ii": 1,
        "mixer-ii-dirt-from-compost": 1,
        "polymerization-plant-plastic-ethanol": 1,
        "assembly-v-mechanical-parts": 1,
        "cooled-caster-ii-steel": 1,
        "oxygen-furnace-ii-steel": 1,
        "arc-furnace-ii-iron-scrap": 1,
        "arc-furnace-ii-iron-ore": 1,
        "crusher-large-iron": 1,
        "wastewater-treatment-toxic-slurry": 1,
        "evaporation-pond-heated-salt-brine": 1,
        [maintenanceStatue.id]: defaultMaintenanceStatueCount,
      },
      activeBuildings: {
        "settling-tank": 2,
        "mill-wheat": 2,
        "baking-unit-bread": 1,
      },
      fixed: [maintenanceStatue.id],
    },
  ],
  defaultPresetId: "yellowcake",
};

export const createGeneralModule = (maintenanceStatueCount: number): Module => {
  const normalizedCount = Math.max(0, Math.trunc(maintenanceStatueCount));

  return {
    ...general,
    builtBuildings: {
      ...general.builtBuildings,
      [maintenanceStatue.id]: normalizedCount,
    },
    presets: general.presets.map((preset) => ({
      ...preset,
      builtBuildings: {
        ...preset.builtBuildings,
        [maintenanceStatue.id]: normalizedCount,
      },
    })),
  };
};
