import { type Module } from "./modules";

export const general: Module = {
  id: "general",
  name: "General",
  description: "Shared production for yellowcake, electronics, and supporting materials",
  buildingTotals: {
    "crusher-large": 3,
    "settling-tank": 2,
    "mixer-ii-acid": 1,
    "assembly-v-electronics-i": 1,
    "assembly-v-electronics-ii": 1,
    "assembly-v-pcb": 1,
    "silicon-reactor-poly-silicon": 4,
    "crystallizer-silicon-wafer": 1,
    "microchip-machine-ii-1a": 1,
    "microchip-machine-ii-1b": 1,
    "microchip-machine-ii-1c": 1,
    "microchip-machine-ii-2a": 1,
    "microchip-machine-ii-2b": 1,
    "microchip-machine-ii-2c": 1,
    "microchip-machine-ii-3a": 1,
    "microchip-machine-ii-3b": 1,
    "microchip-machine-ii-3c": 1,
    "microchip-machine-ii-4a": 1,
    "microchip-machine-ii-4b": 1,
    "microchip-machine-ii-final": 1,
    "assembly-v-electronics-iii": 1,
    "rubber-maker-ethanol": 1,
    "chemical-plant-ii-ethanol": 1,
    "chemical-plant-ii-graphite": 1,
    "copper-electrolysis-acid": 2,
    "waste-sorting-recyclables": 1,
    "arc-furnace-ii-copper-scrap": 1,
    "arc-furnace-ii-copper-ore": 1,
    "metal-caster-ii-copper": 2,
    "crusher-large-copper": 1,
  },
  presets: [
    {
      id: "yellowcake",
      name: "Yellowcake",
      description: "1 of 3 large crushers active + 2 settling tanks with demand-balanced acid",
      buildingTotals: {
        "crusher-large": 3,
        "settling-tank": 2,
        "mixer-ii-acid": 1,
        "assembly-v-electronics-i": 1,
        "assembly-v-electronics-ii": 1,
        "assembly-v-pcb": 1,
        "silicon-reactor-poly-silicon": 4,
        "crystallizer-silicon-wafer": 1,
        "microchip-machine-ii-1a": 1,
        "microchip-machine-ii-1b": 1,
        "microchip-machine-ii-1c": 1,
        "microchip-machine-ii-2a": 1,
        "microchip-machine-ii-2b": 1,
        "microchip-machine-ii-2c": 1,
        "microchip-machine-ii-3a": 1,
        "microchip-machine-ii-3b": 1,
        "microchip-machine-ii-3c": 1,
        "microchip-machine-ii-4a": 1,
        "microchip-machine-ii-4b": 1,
        "microchip-machine-ii-final": 1,
        "assembly-v-electronics-iii": 1,
        "rubber-maker-ethanol": 1,
        "chemical-plant-ii-ethanol": 1,
        "chemical-plant-ii-graphite": 1,
        "copper-electrolysis-acid": 2,
        "waste-sorting-recyclables": 1,
        "arc-furnace-ii-copper-scrap": 1,
        "arc-furnace-ii-copper-ore": 1,
        "metal-caster-ii-copper": 2,
        "crusher-large-copper": 1,
      },
      available: {
        "settling-tank": 2,
      },
      fixed: ["settling-tank"],
    },
  ],
  defaultPresetId: "yellowcake",
};
